### ISSUE TITLE
[bug] Leap global shortcut takes priority over other application shortcuts

### ISSUE THREAD

**Issue by pfych** [jalehman/port#127]
**Bug Description**
Global shortcut for leap takes priority over other application shortcuts

**To Reproduce**
Steps to reproduce the behaviour:
1. Open any application with cmd+/ as a shortcut
2. try to use the shortcut

**Expected Behavior**
The currently focused applications shortcut should take priority

**Environment:**
 - OS: MacOS
 - Version: 11.6
 - Port Version: 1.2.0

**Additional context**
It should be possible to disable or change the global shortcut.

**Comment by Beasta** [comment]
cmd+/ is how i comment code. would be cool if we could just make it custom to whatever we wanted.

**Comment by arthyn** [comment]
Thanks, this is now able to be changed with a setting in the latest release 1.3.
