### ISSUE TITLE
Not a bug, but hear me out.

### ISSUE THREAD

**Issue by odyslam** [jalehman/port#133]
Hey everyone ,

This is an awesome project, as I am using it heavily to run Urbit on my mac. 

I am currently developing [~Home-Urbit](https://github.com/odyslam/homeurbit) and I sort of need something like the port, in the sense that I need an easy way for the user to load their keyfile/pier and start Urbit. 

I want the whole process to be done via a browser, as the Raspberry Pi is intended to lay headless somewhere. Just plug it to Ethernet and Power.

Would it be possible to have a port binary that is accessible via a browser and functions just like the current port? 

Home-Urbit is being developed under a [grant](https://urbit.org/grants/~home-urbit). We can also chat at Assembly :)

**Comment by arthyn** [comment]
Hey there! There's no "easy" way to do this that I'm aware of, but we could probably make some abstractions that would make it easier to build something like this. Basically if we made all the front-end interactions talk to a single API, which I think we almost completely do though I'd maybe change it slightly, we could switch out the IPC calls for actual REST calls. Then we could do something similar on the backend to convert to an HTTP server. 

It's possible this could all live in the same codebase, but we'd have to try it to really see how manageable/unmanageble that'd be. Let's talk at Assembly, that'd be great!

**Comment by odyslam** [comment]
Actually, with the front-end talking to an API, it should be fairly easy to create the backend. 

The MVP could be a simple static server that uses bash scripts to start/stop urbit binaries and the filesystem to store all relevant data. 

What I had in mind is to actually make a simple static website and use minio for uploading/download artifacts. The user would enter the website, upload their artifact and then a script on the device would download the artifact and use it. 

Afterward, we can see about implementing more of Port's features, such as managing multiple ships, etc. 

Can't wait to meet you all :) 

Oh, send me a message at ~sipsen-pilser , so that we connect on Mars as well.
