### ISSUE TITLE
future windows binaries should not include version number in the name

### ISSUE THREAD

**Issue by tinnus-napbus** [jalehman/port#137]
I'm currently update the getting started guide which includes a link to download the windows port binary. I've linked the current version but in future it would be better if it was like the MacOs one eg `port.dmg` so I don't have to update the docs with every release

**Comment by arthyn** [comment]
Ah yeah I'll have to figure out how to get it without version in the name, but I'll get it.

**Comment by tomholford** [comment]
+1, this would be nice for Bridge's "Download Port for Your OS" button. For now, working around it by linking Windows and Linux users here (which redirects to latest tag):

https://github.com/urbit/port/releases/latest

**Comment by arthyn** [comment]
Releases will now have the windows exe named `PortSetup.exe` so they can be permalinked.
