### ISSUE TITLE
Port should warn people booting planets

### ISSUE THREAD

**Issue by arthyn** [jalehman/port#139]
Inexperienced pilots mostly don't know about double booting with keyfiles, we should warn them with a dialog on the planet boot screen after clicking the keyfile field. Something to the effect of "If you've already booted with a keyfile, you should import your planet's pier (folder)." and offer a link to the import existing ship page and a button that says "This keyfile hasn't been used" which basically does what clicking that field does now.

**Comment by arthyn** [comment]
We should also check if we have the same planet name and just straight up prevent booting if found.

**Comment by arthyn** [comment]
Should also have some helpful copy to say where to find their keyfile

> You can find your keyfile inside your Passport. If you don’t have a keyfile, you can download it from Bridge.

**Comment by crites** [comment]
How bad does it mess things up if you do boot your planet on two different machines with the same keyfile?  When first starting out I might have used the same keyfile on a Windows machine and a Ubuntu VM.  Is there anyway to check?  I did end up getting a new keyfile from bridge, but I'd like to keep that to a minimum with the ETH fees involved. :-)

**Comment by arthyn** [comment]
@crites you've probably already figured it out by now, but using the same keyfile twice breaks your ships communications. You'll have to breach and get a new keyfile like you said.

**Comment by crites** [comment]
@arthyn is there anyway to fix this without spending ETH transaction fees to get a key file for each of my planets?

**Comment by arthyn** [comment]
Answered here https://github.com/urbit/port/issues/159#issuecomment-1004452157

**Comment by wistec-bisrum** [comment]
@arthyn I think it might make sense to change the order so "Existing ship" is shown before "Planet".

**Comment by wistec-bisrum** [comment]
And for newcomers, I think it would be great to show examples with the different options. Aka Planet = ~sampel-palnet, so people can pattern match with the identity they have.

**Comment by wistec-bisrum** [comment]
"Unused Planet" etc could also help.

**Comment by wistec-bisrum** [comment]
Btw, these thoughts are from my experience with the boot menu after already having 1 or more ships in the UI. Not the first time onboarding.
