### ISSUE TITLE
Port having trouble booting a planet for the first time-- suspect NAT issues.

### ISSUE THREAD

**Issue by HankoTM** [jalehman/port#143]
**Bug Description*
I'm trying to boot a planet for the first time in port and it seems to be stuck. From the output in the boot screen on port, it seems like it's trying to reach my parent star before the ping times out and it tries again; this has been looping for ~6hrs. See attached screenshot for the output I'm seeing. Other users in the Urbit Community Help channel recommended I start an Issue here, suspecting NAT traversal issues. This seems to track since other users under my parent star report no bugs.

Edit: Later I booted the planet with the CLI so if you look into my planet it will show as booted. I apologize if this makes it harder to track down the bug. 

**Screenshots**
![Screenshot (11)](https://user-images.githubusercontent.com/93146799/138729256-6db6366b-3183-46e2-a7b0-473eb34e906a.png)

**Environment:**
 - OS: Windows 10

**Comment by lycurgus** [comment]
It actually looks like the boot succeeded - `~narsyd-tamnul:dojo>` is the prompt that you would have ended up at after a successful CLI boot (which is basically what Port does internally).

If you go back to the home screen and stop/relaunch the planet, does it correctly load the interface? You should see a page with tiles for "Terminal" and "Groups".

**Comment by HankoTM** [comment]
> It actually looks like the boot succeeded - `~narsyd-tamnul:dojo>` is the prompt that you would have ended up at after a successful CLI boot (which is basically what Port does internally).
> 
> If you go back to the home screen and stop/relaunch the planet, does it correctly load the interface? You should see a page with tiles for "Terminal" and "Groups".

Yes, I went and booted with the CLI and the planet is up now in browser. I will update the initial post to reflect this; the initial issue with Port remains unchanged.

**Comment by lycurgus** [comment]
Ok - once it's booted from the CLI you would need to import the pier (which is the directory that stores your ship's state) into Port, rather than running it again. Probably best to remove the existing Port entry altogether as two separate copies of the same identity can't (shouldn't) be run together, either at the same time or independently. (You can run an identity on multiple machines or via multiple methods - e.g. Port/CLI - you just need to copy the pier back and forth and only ever run the newest copy).

 A CLI run will create a directory with your ship's name (i.e. `narsyd-tamnul`) which appears empty but has some hidden folders containing the data. If the CLI version is working properly you should be able to delete the version in Port and import the CLI-made pier. If you're comfortable to continue using the CLI that is also an option.

If you boot a new comet via Port's boot menu, does it get stuck in the same place? Wondering if it's something specific to planets, perhaps...

**Comment by arthyn** [comment]
Ha @lycurgus you beat me to it.

I think I saw something similar to this with the new windows binary. Sometimes the `http connected...` and `ames connected...` lines fail to spit out correctly and that was my main way of knowing if your ship was up. This just needs to use a more robust way, and I think I know what can be done (hopefully).

Sorry you experienced this @HankoTM. If you want to have your ship in Port later, you can follow @lycurgus 's instructions above, basically shut it down and then in Port select `Existing Ship` in the boot menu here:

![image](https://user-images.githubusercontent.com/5466421/138790479-5b6e1882-da80-403d-a301-9654a8ff4ec9.png)

But you may not be able to do that until this gets fixed.

**Comment by HankoTM** [comment]
> Ok - once it's booted from the CLI you would need to import the pier (which is the directory that stores your ship's state) into Port, rather than running it again. Probably best to remove the existing Port entry altogether as two separate copies of the same identity can't (shouldn't) be run together, either at the same time or independently. (You can run an identity on multiple machines or via multiple methods - e.g. Port/CLI - you just need to copy the pier back and forth and only ever run the newest copy).
> 
> A CLI run will create a directory with your ship's name (i.e. `narsyd-tamnul`) which appears empty but has some hidden folders containing the data. If the CLI version is working properly you should be able to delete the version in Port and import the CLI-made pier. If you're comfortable to continue using the CLI that is also an option.
> 
> If you boot a new comet via Port's boot menu, does it get stuck in the same place? Wondering if it's something specific to planets, perhaps...

Yeah, this is what I ended up doing. I'm fine with CLI for now so I removed the ship from port and things are running smoothly. Yes, the same issue occurs with comets, fwiw. Planet is up and running, so my issue is solved. Should I close this issue or leave it open until the underlying bug is fixed?

**Comment by lycurgus** [comment]
Should be fine to leave this one open for tracking, I think. Glad to hear you're up and running :)

**Comment by arthyn** [comment]
Should be fixed in latest update
