### ISSUE TITLE
[bug] Groups and Bitcoin apps stuck in installing mode

### ISSUE THREAD

**Issue by davecahill** [jalehman/port#151]
**Bug Description**
Terminal app is usable, but both Groups and Bitcoin are not. They both display as "Installing" - for many hours and despite restarts.

**To Reproduce**
Launched a comet, upgraded apps (or chose automatically upgrade, can't remember which).

**Expected Behavior**
Groups and Bitcoin apps are usable.

**Screenshots**
<img width="837" alt="Screen Shot 2021-11-22 at 14 58 29" src="https://user-images.githubusercontent.com/361096/142808432-766df14f-f29c-4b7d-9b49-f70fc945088b.png">

**Environment:**
 - OS: MacOS 
 - Version: 11.6 (Big Sur)
 - Port Version: 1.5.1

Clicking App Info on the apps works, and gives:
- Groups app: 1.0.2
- Bitcoin app: 0.0.1

**Additional context**
No errors in console

.

**Comment by arthyn** [comment]
@davecahill hey there, this is likely an issue on your urbit itself and not with Port. Can you try opening up the terminal and typing these commands?

```
|install (sein:title our now our) %landscape
|install (sein:title our now our) %bitcoin
```

**Comment by davecahill** [comment]
Thanks @arthyn !

The terminal app was stuck on "connecting..." no matter how many times I restarted the comet or the Port app, so I ran terminal from the Manage > Troubleshooting menu, and was able to run the above commands.

After running the commands, running Launch showed no apps at all. After stopping and relaunching, still no apps. But stopping Port and rerunning, now the apps show - thanks!

If it's not a port issue, is there somewhere else I should report it? I don't think I did anything particularly strange, and the system seems to have ended up in a pretty broken state.

**Comment by lycurgus** [comment]
> The terminal app was stuck on "connecting..." no matter how many times I restarted the comet or the Port app

Just wanted to chime in and let you know that this seems to be a widespread issue: urbit/landscape#1316

> If it's not a port issue, is there somewhere else I should report it?

The other two main places to report things are:
- https://github.com/urbit/urbit/issues for core system problems (e.g. networking, failure to install software)
- https://github.com/urbit/landscape/issues for problems with Landscape specifically (i.e. the Groups app)

It's not _super_ critical that things go in the right repo (at least for now, the volume is low enough that things tend to get seen no matter where they are), so if you're not sure what a particular issue relates to, just mention that in the description.

One thing to be aware of for future troubleshooting is that a ship running under Port is still accessible via a web browser - it runs on a local port and Port just wraps/exposes it. You should be able to see which port it's running on by hovering the name of the ship in the main menu - the "interface" port is the one you want. You can then open `http://localhost:<interface port>` in a browser, usually `http://localhost:8080`, to see the same thing Port shows. This may help in terms of being able to open an Incognito window to see if it's a browser storage problem and so on. Broadly if something only happens under Port but not in a browser, it's probably a Port problem. If it happens in both it's probably for either the `urbit/urbit` or `urbit/landscape` repos.
