### ISSUE TITLE
multiple (to be parsed)[bug]

### ISSUE THREAD

**Issue by silheb** [jalehman/port#152]
**Bug Description*
I've experienced general instability with port (macos 12).  comets hang at _connecting..._ for terminal. when opened, port erroneously shows remote ships connected (not true, no processes running, and remote ship offline and inaccessible.)  previously created and viable planets result in _Unable to connect: there may be something wrong with your remote ship_ (it was created on this machine with port).

**Environment:**
 - OS: [MacOS]
 - Version: [12.0.1]
 - Port Version: [1.6.0]

**Additional context**
Happy to troubleshoot, but I probably need guidance on what is most helpful to start with.  For planet issue, debug seems to show local planet is running (I see terminal activity). urbit-worker is gulping 99.8%+ of a cpu, and urbit process is running.  For comet terminal connection issue, again, it appears dojo commands are executing in debug, while comet terminal window seems stuck connecting.

**Comment by arthyn** [comment]
So the terminal app in Urbit actually has a few issues regarding connecting, especially recently. You can always test whether something like this is a Port issue by hovering over the "running" indicator to see what ports the urbit is using and then opening a browser with `http://localhost:{PORT}` replacing {PORT} with what you saw in the tooltip.

Regardless, you can now run a direct terminal through Port (aka not the Urbit app on your home screen), by going to Manage -> Start in terminal. This should always connect.

For the planet issue, that sounds really strange. It sounds like maybe your planet was added as a remote ship which means Port isn't running it at all. Did you actually boot that planet through Port? It shouldn't be possible for a ship in Port to change from local to remote without deleting it first and re-importing as remote (meaning it's just acting as a browser).

If you go to `Manage` on that planet, it should show what URL it's pointing at, does that look familiar?

Either way you can look in `/Users/{username}/Library/Application Support/Port/piers` to see if you can see the folder with your planet. Something also helpful would be if you grab the file at `/Users/{username}/Library/Application Support/Port/db/piers.db` and drop it here, I can take a look.

**Comment by silheb** [comment]
Great feature on the hover to find active port.  

2 different planet issues. One local (birthed/booted on Port), and one remote

The (local) planet that was created in Port on my local machine, and shows a folder pier (whos timestamp updates) will neither launch nor start in terminal.  Shows no port active for it.  

The remote planet (running on a pi in another city) can't be contacted at the moment, but Port still shows it green dot and connected.  The url is correct though (winrym-silheb.arvo.network)

piers.db forwarded in email

**Comment by arthyn** [comment]
So looking at the DB file, it seems you have two ships with the type of "Planet" but are actually comets, which is strange but I guess if you imported them as planets it would technically work.

Other than that I see ~winrym-silheb your remote planet and ~solsel-lasnut which doesn't seem to have a ship name even though it has a status of running which is really weird. So what happens exactly when you click launch on ~solsel-lasnut?

You're right about the connected being wrong, it's fake and just shows up for all remote ships. Probably should just make it real haha, we do check the remote when trying to open it.

**Comment by arthyn** [comment]
Try running with this latest update, if it still isn't working maybe we can have a debug session over video chat

**Comment by arthyn** [comment]
Closing until we hear back
