### ISSUE TITLE
L2 + port: endless %e %authenticated-without-cookie locking boot

### ISSUE THREAD

**Issue by jamesacklin** [jalehman/port#156]
**Describe the bug**
When booting a fresh L2 planet with port, the boot process gets stuck on an endless loop of printing `[%e %authenticated-without-cookie]`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Claim a new L2 planet using an invite code.
2. Download the keyfile/passport.
3. Boot a new planet using port and the new keyfile.
4. Wait and observe; the planet never boots into Landscape and hangs on the loading screen while printing into infinity.

**Expected behaviour**
A clean boot process which follows the standard sequence.

**Screenshots**
stdout (reverse-chron, sorry): https://pastebin.com/raw/Z5nkg09d

**System (please supply the following information, if relevant):**
 - Windows 10 Home (64-bit), port 1.6, urbit 1.8

**Comment by arthyn** [comment]
Should be fixed in latest

**Comment by phlextro** [comment]
Im having this issue booting up a new planet on build 1.9.1, using linux. Also when this endless loop occurs, port consumes more and more memory, up at 2.5 GB after 15 minutes. I tried port on my machine first using a comet and no problems there.

Update: Am able to run planet by starting with terminal and going through web interface

**Comment by planefun2** [comment]
Having this same issue with the error message.  i can get in but when i browse groups the app crashes. Win10 client.

**Comment by arthyn** [comment]
@planefun2 sorry about that, there's currently a bug in the Urbit binary which seems to shutdown at random. you can see the issue tracking it here: https://github.com/urbit/urbit/issues/5822
