### ISSUE TITLE
Landscape fails to load

### ISSUE THREAD

**Issue by saunic** [jalehman/port#158]
**Describe the bug**
Landscape won't load (get's stuck in loading screen, despite computer restart 
*Include a screenshot or stack trace if possible.*
![image](https://user-images.githubusercontent.com/71407101/146458707-63c0f9a4-3916-4fa1-ad1e-8f1bb0e925a3.png)
![image](https://user-images.githubusercontent.com/71407101/146458517-6b34a2c1-372a-4382-914e-4c4d90725001.png)

**To Reproduce**
1. Click on Port Desktop icon
2. Click Launch
3. Loading animation starts and never ends

**Expected behavior**
To end up on the app homepage

**Operating context**
 - Device: ROG Zephyrus G15
 - OS: Windows 10
 - Landscape Version v1.6.0

**Additional context**
-

**Comment by saunic** [comment]
3rd new comet has stopped working. I updated Port. 
Here's the new console screenshot
![image](https://user-images.githubusercontent.com/71407101/147249724-315a16cc-4200-4eb1-9bad-772009b1f246.png)

**Comment by arthyn** [comment]
I'm not sure what happened to your first two comets, but this last one was a bug with the 1.7.0 release. A fix was deployed with 1.7.1, @saunic try booting another and see if that works. 

Do you remember doing anything in particular with your other comets that could have broken them? Like possibly booting them outside Port while still running or something similar?

**Comment by saunic** [comment]
> 

The last one I booted, I tried using in browser but other than that I usually just use Port. They don't break mid-use (when Port is open), they break at times when I exit Port and then try opening it again later on in the day. Hopefully that makes sense.

**Comment by arthyn** [comment]
@saunic this sounds pretty strange. Would it be possible to have a video call? If so email me at hunter @ tlon.io

**Comment by Conviare** [comment]
Having similar issue after updating OS.  Temp disable apps System, Terminal, Groups and BTC using temp disable and update option.  Now reopening from port never loads Landscape and throws gateway timeout.  Nothing at localhost

**Comment by arthyn** [comment]
@Conviare can you try going to "Manage" on the ship experiencing this and then click "Start in Terminal" and put the output here?

**Comment by Conviare** [comment]
/linux/urbit /home/richardlb/snap/port/common/.config/Port/conviare-planet
~
urbit 1.8
boot: home is /home/richardlb/snap/port/common/.config/Port/conviare-planet
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/857.063.424
boot: installed 348 jets
---------------- playback starting ----------------
pier: replaying events 181766-181776
gall: not running %docket yet, got %leave
gall: not running %docket yet, got %leave
gall: not running %docket yet, got %leave
gall: not running %docket yet, got %leave
gall: not running %docket yet, got %leave
pier: (181776): play: done
---------------- playback complete ----------------
vere: checking version compatibility
lmdb: write failed on event 181777
unix: stopping process 88845, live in /home/richardlb/snap/port/common/.config/Port/conviare-planet...
unix: stopped old process 88845
ames: live on 52195
pier: disk write bail

home: bailing out
Aborted (core dumped)
richardlb@richard-hpcompaqelite8300sff:~$

**Comment by Conviare** [comment]
> @Conviare can you try going to "Manage" on the ship experiencing this and then click "Start in Terminal" and put the output here?

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

/linux/urbit /home/richardlb/snap/port/common/.config/Port/conviare-planetources/
~
urbit 1.8
boot: home is /home/richardlb/snap/port/common/.config/Port/conviare-planet
loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622
lite: final state 7b144622
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/857.063.424
boot: installed 348 jets
vere: checking version compatibility
ames: live on 36871
gall: not running %docket yet, got %leave
http: web interface live on http://localhost:8080
http: loopback live on http://localhost:12321
pier (223344): live
ames: czar feb.urbit.org: ip .34.82.25.47
ames: czar ten.urbit.org: ip .104.196.239.18
ames: czar zod.urbit.org: ip .35.247.119.159
ames: czar rel.urbit.org: ip .34.83.230.207
ames: czar bus.urbit.org: ip .35.247.126.229
ames: czar rys.urbit.org: ip .23.239.12.212
ames: czar rep.urbit.org: ip .198.199.121.116
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~feb not responding still trying
; ~feb is ok
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~feb not responding still trying
; ~feb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~feb not responding still trying
; ~feb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
gall: not running %docket yet, got %leave
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~feb not responding still trying
; ~feb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~feb not responding still trying
; ~feb is ok
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~feb not responding still trying
; ~feb is ok
; ~feb not responding still trying
; ~feb is ok
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~hidfeb not responding still trying
; ~hidfeb is ok
gall: not running %docket yet, got %leave
; ~hidfeb not responding still trying
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~hidfeb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~feb not responding still trying
; ~feb is ok
; ~feb not responding still trying
; ~feb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~feb not responding still trying
; ~feb is ok
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~feb not responding still trying
; ~feb is ok
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
; ~hidfeb not responding still trying
; ~hidfeb is ok
; ~hidfeb not responding still trying
; ~hidfeb is ok
gall: not running %docket yet, got %leave
[%e %authenticated-without-cookie]
gall: not running %docket yet, got %watch
gall: not running %docket yet, got %poke
~minrun-ticdev:dojo>

**Comment by arthyn** [comment]
@Conviare looks like that second run actually booted, is it working for you?

**Comment by Conviare** [comment]
No Landscape never populates apps, gateway timeout.

**Comment by arthyn** [comment]
@Conviare if you still have the terminal open, try running `|rein %garden, =liv |` and then after it finishes `|rein %garden`

**Comment by Conviare** [comment]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/7/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/14/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/14/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/14/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/15/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/15/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/15/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/16/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/16/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/16/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/17/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/17/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/17/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/18/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/18/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/18/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/19/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/19/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/19/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/20/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/20/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/20/1]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/14/2]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/14/2]]
[%invalid-outstanding-connection ~[//http-server/0vv.rjjmm/14/2]]
[%invalid-outstanding-connection ~[//http-server/0v1t.c0eha/1/1]]
[%invalid-outstanding-connection ~[//http-server/0v1t.c0eha/1/1]]
[%invalid-outstanding-connection ~[//http-server/0v1t.c0eha/1/1]]
gall: reviving %treaty
gall: reviving %hark-store
eyre: removing watch for non-existent channel 1644787251-477231 on hark-store
eyre: removing watch for non-existent channel 1644787599-c9db72 on hark-store
eyre: removing watch for non-existent channel 1644787599-c9db72 on hark-store
eyre: removing watch for non-existent channel 1644787251-477231 on hark-store
eyre: removing watch for non-existent channel 1644787616-d253d7 on hark-store
gall: %notify dozing, got %fact
eyre: removing watch for non-existent channel 1644769924-d77cb6 on hark-store
eyre: removing watch for non-existent channel 1644769924-d77cb6 on hark-store
eyre: removing watch for non-existent channel 1644773053-b0728d on hark-store
gall: %notify dozing, got %fact
eyre: removing watch for non-existent channel 1644769517-f5a714 on hark-store
eyre: removing watch for non-existent channel 1644769517-f5a714 on hark-store
gall: reviving %hark-system-hook
gall: reviving %settings-store
docket: fetching %http glob for %garden desk
> |rein %garden
>=
crud: %eyre-no-channel event failed
id='1644787599-c9db72'
crud: %eyre-no-channel event failed
id='1644787599-c9db72'

**Comment by arthyn** [comment]
Are you able to access it in Port or at http://localhost:8080/ now? Or no change?

**Comment by Conviare** [comment]
Launch works now but no apps and 
nothing on localhost:8080

current url from Landcape http://localhost:8080/apps/grid/

**Comment by Conviare** [comment]
Can connect to localhost:8080 using urbit visor 
localhost:8080/apps/grid/ would not connect thru urbit visor

**Comment by Conviare** [comment]
Back to where I started.

[System](http://localhost:8080/apps/grid/)
The following (4) apps blocked a System Update:
System

[Terminal](http://localhost:8080/apps/webterm/)

[Groups](http://localhost:8080/apps/landscape/)


[Bitcoin](http://localhost:8080/apps/bitcoin/)

In order to proceed with the System Update, you’ll need to temporarily archive these apps, which will render them unusable, but with data intact.

Archived apps will automatically un-archive and resume operation when their developer provides an app update.

Dismiss   Archive (4) apps and Apply System Update

**Comment by arthyn** [comment]
@Conviare do you mind getting on a call real quick? https://meet.google.com/omw-ncbv-vmc

**Comment by Conviare** [comment]
Cool!  Up and running with your help.  Thanks

**Comment by arthyn** [comment]
Deployed something to help avoid this, but a true fix will have to come from the urbit runtime in a few weeks.
