### ISSUE TITLE
[bug] `npm install` fails

### ISSUE THREAD

**Issue by vincepmartin** [jalehman/port#162]
**Bug Description*
Problem with `eslint` package when doing `npm install`

```
> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: port@1.7.1
npm ERR! Found: eslint@7.28.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.6.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0" from electron-root-path@1.0.16
npm ERR! node_modules/electron-root-path
npm ERR!   electron-root-path@"^1.0.16" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/robotburrito/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/robotburrito/.npm/_logs/2022-01-29T21_49_52_526Z-debug-0.log
```
**To Reproduce**
1. Pull down code
2. run `npm install`

**Expected Behavior**
Should install packages and let me begin to contribute to the project :)

**Screenshots**

**Environment:**
 - OS: GNU/Linux `Linux pop-os 5.15.11-76051511-generic #202112220937~1640185481~21.10~b3a2c21 SMP Wed Dec 22 15:41:49 U x86_64 x86_64 x86_64 GNU/Linux`
  - Version:
 - Port Version: [e.g. 1.7.1]

**Additional context**
If it helps I am using
npm: 8.3.1
node: v17.4.0

**Comment by vincepmartin** [comment]
So this ended up being my fault, I was not aware that this project was using yarn.  Apologies for submitting this.

The steps I took to get this working was the following, maybe this can help someone else out.  Also I'd be happy to write up some documentation and maybe update the readme if you think that is appropriate.

1. Use node version ^16, it seems that ^17 does not play well with the project.
2. install yarn via `npm install -g yarn`
3. install `node-gyp` via `yarn global add node-gyp`, a side note, make sure you have Python 3!
4. start the project via `yarn run start` and you are good to go!

**Comment by arthyn** [comment]
@vincepmartin if you want to write that up in the readme that would be awesome!

**Comment by vincepmartin** [comment]
> @vincepmartin if you want to write that up in the readme that would be awesome!
No problem, took a shot at it.  Check out the pull at https://github.com/urbit/port/pull/183
