### ISSUE TITLE
[Bug] Including a leading ~ in the name of a new ship breaks boot with key mismatch

### ISSUE THREAD

**Issue by lycurgus** [jalehman/port#164]
**Bug Description*
Booting a pier whose shipName has a leading ~ breaks the boot.

**To Reproduce**
1. Boot a new planet
2. Enter the planet name with a leading `~`
3. Proceed with boot
4. Receive a key mismatch error

**Expected Behavior**
Normal boot without error

**Environment:**
 - OS: unspecified
 - Version: unspecified
 - Port Version: unspecified

**Additional context**
Reported in UC by `~tacsul_binzod` : web+urbitgraph://group/~bitbet-bolbel/urbit-community/graph/~dopzod/urbit-help/170141184505483066186673589928308244480

**Comment by arthyn** [comment]
I don't think this actually prevents booting, might have been an issue with L2 syncing.
