### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by dozreg-toplud** [jalehman/port#165]
**Bug Description**
Launching second ship on Windows 10 leads to crash.

**To Reproduce**
1. Mine two comets using Port (I booted first one, stopped it, then booted second.) Install OTA updates:
    `|ota (sein:title our now our) %kids`
2. Stop both comets.
3. Launch first comet. While first comet is running, launch the second one (cmd or Port)
4. Logs of the second comet:

> urbit 1.8
> boot: home is second_comet_test
> loom: mapped 2048MB
> lite: arvo formula 27e494c5
> lite: core 7b144622
> lite: final state 7b144622
> loom: mapped 2048MB
> boot: protected loom
> live: loaded: GB/1.262.288.896
> boot: installed 348 jets
> vere: checking version compatibility
> ames: live on 55420
> eyre: canceling ~[//http-server/0vb.t7aft/78/1]
> http: listen: invalid argument
> http: listen: invalid argument
> pier (163670): live
> ames: czar zod.urbit.org: ip .35.247.119.159
> ~hinrup_samzod:dojo> address 000001cd17d1deb0 out of loom!
> loom: [0000028000000000 : 0000028080000000)
> Assertion '0' failed in noun/events.c:128
> home: bailing out

After the crash, the second comet still can be launched normally if the first one is stopped before the launch.

**Expected Behavior**
I assume, both comets should run normally without interfering with each other.

**Environment:**
 - OS: Windows 10
 - Version: Urbit 1.8
 - Port Version: 1.7.1

**Additional context**
Checked the developer tools, didn't find anything of interest.

**Comment by arthyn** [comment]
Deployed something to help avoid this, but a true fix will have to come from the urbit runtime in a few weeks.
