### ISSUE TITLE
Booting hang up on new Planet - Message - urbit.org/using/install/#about-swap-space for adding swap space

### ISSUE THREAD

**Issue by nickcavein** [jalehman/port#174]
Hi, I'm trying to boot a new planet and am getting this message urbit.org/using/install/#about-swap-space for adding swap space. Try to boot on Windows Could not find anything at this link. Never used Urbit before, not a programmer so very newbie. Would appreciate some help as I'm eager to learn about Urbit and use it. I've attached the error and stuck boot screen. Thanks!
![system](https://user-images.githubusercontent.com/101351247/157714707-d285969c-0a96-4e45-b2fb-6c59355c9dff.JPG)
![Urbit_Boot_Fail](https://user-images.githubusercontent.com/101351247/157714767-9512fda2-1e90-4113-ad0a-aacbbc82a6d0.JPG)

**Comment by arthyn** [comment]
@nickcavein Hey there, it's likely you hit the RAM limit. Unfortunately the way that urbit works right now is that takes a full 2048 MB of RAM even though it doesn't use all of it. You may be able to run it if you reduced programs running, but it may be hard with only 4 GB.

**Comment by nickcavein** [comment]
Is it possible for me to try this on a different computer system? I have another one that should meet the RAM requirements.

**Comment by arthyn** [comment]
In this case I believe it is safe to try again on another machine because you didn't make it far enough in the boot process that you actually were communicating on the network.

**Comment by nickcavein** [comment]
Ok, I'll give it a go and let you know who it went.
