### ISSUE TITLE
[bug]Boot fresh ID: Can't choose keyfile due to illegible font display. 

### ISSUE THREAD

**Issue by julesss-coder** [jalehman/port#179]
**Bug Description*
1. After starting Port and clicking "Boot a fresh ID", I click "Choose keyfile". The file manager opens, but all characters are replaced with rectangles, so I can't find the file. See screenshot: 
![Urbit screenshot](https://user-images.githubusercontent.com/67640854/159804406-55f835ce-1479-4462-b566-d7b3eb4ab340.png)

2. Then, Port crashes. The terminal shows many "fontconfig errors" and "fontconfig warnings", see screenshot:
![Port fontconfig errors](https://user-images.githubusercontent.com/67640854/159806189-f8e987b6-e5cb-4a99-b007-f60338458526.png)

**To Reproduce**
1. Start Port
2. Click on 'Boot a fresh ID.'
3. Click on "Choose keyfile".
4. See illegible characters in file explorer window
5. See Port crash and - if you started Port in the terminal - check terminal for error messages.

**Expected Behavior**
File explorer opens, characters are legible, I can find and choose the keyfile.

**Screenshots**
See above.

**Environment:**
 - OS: Ubuntu
 - Version: 20.04.4 LTS, 64-bit
 - Port Version: 1.8.0, installed via snap, as described here: https://urbit.org/getting-started#port 

**Context**
I don't know how to install Port on Linux any other way than via Snap, as I lack the technical knowledge. I hope you can help me boot my planet even though I'm a newbie to all this!

**Comment by lycurgus** [comment]
Based on an issue thread from another project (https://github.com/iced-rs/iced/issues/386) it seems like you might need to install the `libfontconfig-dev` package. Might also need to log out and in, or restart the machine, to get it to reload the fonts after installing that package.

**Comment by julesss-coder** [comment]
Hi there, thank you! 
I installed `libfontconfig-dev` and restarted my computer, but the problem persists. 
(I was able to boot my urbit planet anyway, using some guesswork.)

**Comment by lycurgus** [comment]
Glad to hear you got the planet booted; sorry my advice wasn't helpful. I also found this reddit thread which mentions moving the fonts folder and reinstalling fontconfig as a possible solution: https://www.reddit.com/r/Ubuntu/comments/t7rgij/cant_install_most_of_the_snap_packages_recently/

I don't know if that's an actual solution or just a workaround - it might be something @arthyn needs to modify/update in the Port snap itself instead.
