### ISSUE TITLE
Port having trouble booting planet for the first time

### ISSUE THREAD

**Issue by nmeserve** [jalehman/port#189]
I am attempting to boot my planet for the first time using Windows Port V1.8.0 but it is stuck trying to connect with "~polbel" and has been for over 1 hour.

![sevrtDI](https://user-images.githubusercontent.com/45642364/162764538-17307b64-5c51-4c47-977a-7b99527b93ea.png)

Currently running Windows 10 version 10.0.19043

Edit:  I booted a new Comet using this Port and had no issues so this issue only relates to booting a new Planet.

**Comment by arthyn** [comment]
So it looks like your planet has actually booted, but Port didn't detect it for some reason. If you open a browser and go to http://localhost:80 you should see it.

Can you click the little bug in the bottom right hand corner? It should pop open two dev tools windows one in this window and another for the background process. In the dev tools console for the background process, there should be a dropdown:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/5466421/162767202-08a667dc-3a06-46f4-9d4a-043cc98072a8.png">

Try clicking "Default Levels" and change it to only show errors, then post a screen shot of that here.

**Comment by nmeserve** [comment]
![LBpeGuM](https://user-images.githubusercontent.com/45642364/162768345-1d31d08c-2a25-47bb-af60-a18f1b11f83a.png)

I tried logging in using localhost:80 but that appears to be trying to log me into the Comet I booted prior to trying to boot the Planet.

**Comment by arthyn** [comment]
If you go to your home screen does it show your comet as running? It should have prevented you from booting a another ship until the comet was stopped.

**Comment by nmeserve** [comment]
The Comet was still running.  I just manually stopped it.  Should I restart the Planet boot process?

**Comment by arthyn** [comment]
No don't restart the boot process. At this point your planet is actually booted there's a bug in the urbit binary on windows that prevents it from binding the right web ports if another ship is running, which also fools port into thinking its not running. I think somehow your comet didn't get stopped and then when you tried to boot it failed binding those ports. Let me think of a way to recover from here.

**Comment by arthyn** [comment]
If you open file explorer and go to `C:\Users\%USERNAME%\AppData\Roaming\Port\piers` you should see two folders, one with your comet and one that's your planet. In the planet folder right click > New > text document, then name the file exactly `.http.ports`. Then double click that file and it should open notepad. Then add the following lines and save:

```
12321 insecure loopback
80 insecure public
```

After a few moments, Port will then finish the boot process hopefully and will show a launch button. At this point close port and also open task manager and kill any processes that are labelled urbit or port. Once all are gone, then you should be able to boot port and open your planet. 

Sorry for all this, it's kinda two bugs in one. We're hoping to make some of this boot recovery better soon.

**Comment by nmeserve** [comment]
Followed instruction:
![l9Fiuxg](https://user-images.githubusercontent.com/45642364/162777935-29367760-7a9f-4605-9c94-b62c729c5791.png)
s

![qOUT4sU](https://user-images.githubusercontent.com/45642364/162778001-3e1102e6-e2ba-498d-8cfd-1b8a8afe5181.png)

Boot process still running after a few minutes and showing "not responding".  Do I need to delete the existing .http.ports file or maybe it just needs more time?

**Comment by arthyn** [comment]
Ok lets try one other thing. Delete those .http.ports files and clear all urbit/port process from task manager (make sure you go into the detailed view). Then go to the manage screen for your planet, and hit eject. This should give you a zip of your pier. Unzip it and then from the boot menu choose existing ship.

**Comment by nmeserve** [comment]
This process worked.  Planet access is restored!  Thanks for helping arthyn

**Comment by arthyn** [comment]
Np, glad to hear!

**Comment by latter-bolden** [comment]
@arthyn it seems like we could add more defensive checks to make sure one ship is running at a time in windows. But I'm also hesitant to make the logic more complex when this is really something that should be fixed in the urbit binary itself.

**Comment by arthyn** [comment]
Yeah exactly, that's why I just did a front-end pass to try and prevent it, because the issue is actively (I think) being worked on in the binary. The issue we can glean from this is that stopping a ship could be more robust probably, not sure why that failed.

**Comment by sibwyl-batrep** [comment]
My friend has the same issue. He got the master ticket via invite. Started the booting with Port on Windows today. several hours later it still hasnt ended. 
2 ways of dealing with the problem mentioned here earlier didn't help. Clicking "eject" -> nothing happens.
@arthyn

**Comment by sibwyl-batrep** [comment]
Any ideas, @arthyn ? I don't won't to open another thread for the same issue, so

**Comment by arthyn** [comment]
@sibwyl-batrep thanks for pinging me, I meant to come back to this and forgot. It's likely his planet actually did boot, but Port failed to detect it because of a few bugs in Windows.

He can try closing Port, open up task manager and close any process named Port/urbit if there are any, and then navigate to `%USERPROFILE%\AppData\Roaming\Port\piers`. There should be a folder named the same as his planet, he should move this out of the folder to somewhere easy to access. Then reopen Port and click manage on the "booting" planet, and click "Delete Permanently". Since he moved the folder this will just delete the entry for the ship. Now he can add the ship from the menu as an existing ship where he gives it the folder he moved.  Hopefully this works, if not let me know. I'm unsure what's up with eject but we'll take a look.
