### ISSUE TITLE
Windows fails to eject planet

### ISSUE THREAD

**Issue by arthyn** [jalehman/port#199]

**Comment by latter-bolden** [comment]
@arthyn do you have any steps to reproduce? It seems to be working for me locally (both in dev and 1.9 pre-release .exe)

**Comment by arthyn** [comment]
Seems to be happening for people who's planets have failed to boot because of the port binding bug maybe?

**Comment by latter-bolden** [comment]
Gotcha, I now see the comments this was in reference to.

Looks when you eject, we first try to stop the pier and if marked as booting, it sends a signal to kill the boot process. Our problem is Windows doesn't recognize unix signals so the function throws.

I'm looking into changing the way we handle Windows processes rn anyway for #136, so I'll roll a fix for this into that PR.
