### ISSUE TITLE
[bug] Port installed using Flatpak will not start

### ISSUE THREAD

**Issue by sink666** [jalehman/port#210]
**Bug Description**
`$ flatpak run org.urbit.port 
[13 zypak-sandbox] Failed to send spawn request to supervisor: Bad file descriptor (errno 9)
/app/bin/electron-wrapper: line 3:     3 Trace/breakpoint trap   zypak-wrapper "port" "$@"
[11:0100/000000.757631:ERROR:zygote_linux.cc(646)] write: Broken pipe (32)`

Port will not start when called from the cli or when using the desktop file provided when installed.

**To Reproduce**
1. Install Port from the provided flatpak file
2. Attempt to run from either the desktop file or from the cli or from the cli with provided arguments from the desktop file
3. Port will fail to run with the above error.

**Environment:**
 - OS: Void Linux
 - Version: Linux 5.15.41_1
 - Port Version: v1.9.0

**Additional context**
I installed flatpak fresh, I've never used it before. Perhaps I am missing something regarding the setup. I added flathub as a remote and it downloaded what I assumed were all the dependencies it needed when I installed Port.

The desktop file does not have an icon even though the icon is provided, I checked it was at least installed but I am not sure how flatpak handles icons and desktop files.

**Comment by coryellcp** [comment]
I am having same issue on fedora 36. I tried to clone the repo and troubleshoot but am having problems with yarn install. I've installed node-gyp but am still having errors when trying to install.

**Comment by latter-bolden** [comment]
Thanks for submitting this!

Problem was due to a stale dependency in our build system. A fix for this as well as the missing app icon are in place and will be included in our next patch release.

Should be out later this week, but in the meantime, I'd recommend using the Snap build if possible.

**Comment by sink666** [comment]
great! that should be enough to close this, then.
