### ISSUE TITLE
Can't connect to landscape

### ISSUE THREAD

**Issue by pdcollins90** [jalehman/port#214]
Hi all, sorry to be a total noob but I can't see anything obvious about this on github.  On MacOS Catalina 10.15.7.  Can boot planet via Port but landscape is blank (do not see icons for terminal/groups/bitcoin), when I log into localhost apps are visible but read "errored".  |hi ~zod or to my 'sponsor' is successful.  I've tried installing on a different computer/same OS and also factory resetted but nothing works. I've no skills and am a bit lost : ( any ideas?

In case this is an issue with urbit itself when I +trouble this is the output:

> +trouble
%bitcoin
  /sys/kelvin:      [%zuse 418]
  base hash:        0vv.kn79e.1sm9i.ut8pu.pc10d.i6i7b.jqg8j.q5qvm.950po.uhm1e.n3qon
  %cz hash:         0vv.kn79e.1sm9i.ut8pu.pc10d.i6i7b.jqg8j.q5qvm.950po.uhm1e.n3qon
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  [~ ~mister-dister-dozzod-dozzod]
  updates:          tracking
  source ship:      ~mister-dister-dozzod-dozzod
  source desk:      %bitcoin
  source aeon:      5
  pending updates:  ~
::
%base
  /sys/kelvin:      [%zuse 418]
  base hash:        0v1v.p3a22.iv754.lt3ot.hpbee.0elcg.orl5e.fakce.r1pb5.sg0kt.46vqk
  %cz hash:         0v1v.p3a22.iv754.lt3ot.hpbee.0elcg.orl5e.fakce.r1pb5.sg0kt.46vqk
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~zod
  source desk:      %kids
  source aeon:      120
  pending updates:  ~
::
%landscape
  /sys/kelvin:      [%zuse 418]
  base hash:        0vt.1ivo6.0pj6r.qeavd.e30q1.crqu7.5qc5l.gvs0j.aulvu.joe2j.pa66j
  %cz hash:         0vt.1ivo6.0pj6r.qeavd.e30q1.crqu7.5qc5l.gvs0j.aulvu.joe2j.pa66j
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~litzod
  source desk:      %landscape
  source aeon:      24
  pending updates:  ~
::
%webterm
  /sys/kelvin:      [%zuse 418]
  base hash:        0vb.81mgj.s695n.fuiqg.ddsd4.1oec7.kai2j.aqh8c.2h3u6.ndam6.mndil
  %cz hash:         0vb.81mgj.s695n.fuiqg.ddsd4.1oec7.kai2j.aqh8c.2h3u6.ndam6.mndil
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~litzod
  source desk:      %webterm
  source aeon:      6
  pending updates:  ~
::
%garden
  /sys/kelvin:      [%zuse 418]
  base hash:        0vk.ltcfc.a5mn5.6r5st.n5373.veo4f.knnsj.rjaeu.bamr6.pbuhq.qfvch
  %cz hash:         0vk.ltcfc.a5mn5.6r5st.n5373.veo4f.knnsj.rjaeu.bamr6.pbuhq.qfvch
  app status:       running
  force on:         ~
  force off:        ~
  publishing ship:  ~
  updates:          tracking
  source ship:      ~litzod
  source desk:      %garden
  source aeon:      19
  pending updates:  ~
::
%kids %cz hash:     0v1v.p3a22.iv754.lt3ot.hpbee.0elcg.orl5e.fakce.r1pb5.sg0kt.46vqk

<img width="1271" alt="Screenshot 2022-06-13 at 12 48 09" src="https://user-images.githubusercontent.com/83783931/173387731-58b54071-f43b-413c-820c-7d4a3fe599d2.png">
<img width="1050" alt="Screenshot 2022-06-13 at 15 08 52" src="https://user-images.githubusercontent.com/83783931/173387751-8ebaca5b-70df-406c-926a-92f2ebe2cdbb.png">

**Comment by latter-bolden** [comment]
Thanks for reporting this! I'm guessing this was right after booting for the first time? 

We've had a few reports of longer than normal blank screening now, but I need to investigate. Wondering if it's related to new 1.9 Urbit binary release we included with this version of Port.

The apps erroring is unusual though. Nothing jumps out to me at first glance in your logs, but I'm going to try to reproduce.

**Comment by pdcollins90** [comment]
Hi

Tbh I tried on my MacBook but I can’t remember exactly what the problem
was. Then factory reset it and tried again on iMac, then when this happened
I factory reset again then got stuck again here….

Kind regards

P

**Comment by infodweeb** [comment]
I was blank-screening right after booting for the first time, but I think I just didn't know how to operate. In the startup screen that showed my one ship, I hit the "Open" box and then Landscape appeared.

**Comment by latter-bolden** [comment]
We pushed out a patch release that should fix this. Can you update to [1.9.1](https://github.com/urbit/port/releases/tag/v1.9.1) and let me know if you're still experiencing the issue?

**Comment by infodweeb** [comment]
Thank you latterbolden.  I'm such a noob I can't say that this fixed the issue, because I don't understand the issue.  I get the three boxes to look at Terminal, Groups, Bitcoin.  I'm interested in Groups, finding Groups where I might fit in with that community, but it seems the only way I can view a group is if I have an invitation link from somebody in the group.  I can't get those invitations if no one knows I exist.  I can't even find instructions for how to navigate the Urbit universe.  I'm totally locked out.

**Comment by latter-bolden** [comment]
I hear ya! Can definitely be a little overwhelming and esoteric when joining solo. 

If you are able to get into Groups, try adding `~rondev/group-discovery` using the "Join Group" button — that's the most active group directory I know of. Also feel free to message me (`~latter-bolden`) if you have any other questions or need help :)

**Comment by infodweeb** [comment]
Yeehaw, thank you latterbolden, you broke the logjam for me, I'll be working with this group for weeks just to see all the potentials.

------- Original Message -------

**Comment by latter-bolden** [comment]
Sure thing, happy to help! Glad you were able to get on.

Gonna go ahead and close this for now, @pdcollins90 feel free to comment otherwise if you're still experiencing the issue.
