### ISSUE TITLE
Can't join any groups or install any apps

### ISSUE THREAD

**Issue by seraphimofbrooklyn** [jalehman/port#215]
Hi all,

Completely new to urbit and trying to join Justin Murphy's group for some tutorials but I can't join any group, including the groups like urbit-community (see screenshot). No idea what I am doing wrong. Could someone help? Thanks 

![image](https://user-images.githubusercontent.com/72720867/175656938-21b80cc3-c345-452f-b73d-25c9eeae9419.png)

**Comment by latter-bolden** [comment]
Hey @seraphimofbrooklyn, sorry for the late reply. Were you able to get this resolved?

Not sure this is Port related, but I'd need more info to help diagnose. In the groups window, if you open the dev tools (View > Toggle Dev Tools) and navigate to the Console tab, are there any errors?

**Comment by seraphimofbrooklyn** [comment]
Hi,

I did some more research and it may be a problem with my end but its a bit hard to confirm given my lack of knowledge of the Urbit platform. I have bought a planet, but I do not have a "hosting provider". If I do not have a hosting manager would this affect my ability to "connect" to the Urbit network, hence not allowing me to join groups/install apps?

Best,

Seraphim
________________________________

**Comment by critesjosh** [comment]
I am also unable to join groups or send messages. Here's what's in my dev console. I installed port on my linux machine using snap. This is with a fresh planet.

![Screenshot from 2022-08-17 11-06-10](https://user-images.githubusercontent.com/18372439/185175132-50353d5e-cc47-4c68-b5b5-54d54037d4b9.png)

**Comment by arthyn** [comment]
This looks like your ship was maybe still behind on some OTAs

**Comment by critesjosh** [comment]
Is there a way to make the OTAs happen? I leave port running but still seeing this

**Comment by arthyn** [comment]
Oh actually I just realized in your group join there are two ~ for some reason try ~bitbet-bolbel/urbit-community

**Comment by critesjosh** [comment]
hmm thats strange because i just copied the join URL from another instance of landscape connected to a different ship. I removed the ~ from the url and it work. thanks! :man_facepalming:
