### ISSUE TITLE
opening ship leads to blank screen

### ISSUE THREAD

**Issue by arthyn** [jalehman/port#217]
**Bug Description**
It seems that ships are erroneously being detected as running when they really aren't. When we try to open Landscape you then get a blank screen because the connection fails. It seems we just eat the error instead of detecting that it's actually offline.

**To Reproduce**
1. Start a ship
2. Close Port
3. Kill it with task manager
4. Open Port
5. Click "Open" on same ship that should be labelled running

**Expected Behavior**

**Screenshots**
![Screen Shot 2022-07-05 at 11 20 36 AM](https://user-images.githubusercontent.com/5466421/177373435-8849b816-8dcf-4820-8b1c-a9a36634f4a6.png)

**Environment:**
 - OS: MacOS
 - Version: 11.6.2
 - Port Version: 1.9

**Comment by SkramzHH** [comment]
Im having this issue as well. Im totally new to urbit and i dont know the 1st thing about coding or anything else. I just think urbit is very cool. After my initial boot i was able to access landscape and everything was cool, but i somehow got disconnected & now i only get a blank screen when i open my ship. Unsure of how to proceed.

**Comment by arthyn** [comment]
@SkramzHH if you go to manage and click stop does it seem to stop your ship? And if so, try clicking boot after doing that. If it doesn't seem to stop, close port and try opening up task manager or activity manager on your computer and kill any urbit processes, then reopen port and try stopping again.

**Comment by SkramzHH** [comment]
@arthyn okay its semi functional now. I think* its downloading Paldev, but my groups page is showing up blank now. Seems like yall are getting it together, hopefully it'll be back to functioning properly soon :) Keep up the cool & great work.
