### ISSUE TITLE
[feature request] open a public address from port so that I can log in on my mobile device

### ISSUE THREAD

**Issue by trosel** [jalehman/port#220]
Users can log in to urbit mobile apps today with addresses generated by urbit running on a VPS.

I want to be able to log into an urbit mobile app by entering an address generated by port.

None of the hassle of maintaining a VPS, all of the pleasure of multi-device usage.

As long as my computer running port stays turned on, I should be able to use urbit on my mobile device

**Comment by arthyn** [comment]
This would be really amazing, but it's not really feasible for us to do here by itself. @latterbolden may be working on a solution, but it would have to be outside of port I think.
