### ISSUE TITLE
[bug] Are Port users stuck on 419?

### ISSUE THREAD

**Issue by gtimoth** [jalehman/port#225]
# **Bug Description**

Maybe Port users are stuck on an old binary? I'm guessing ```get-urbit.sh``` only runs once on initial install, which for many users was before the release of 1.9

potentially related: #215

**Comment by arthyn** [comment]
They shouldn't be, the get-urbit.sh is run on deploy. Our last deploy was 1.9.1 which uses the 1.10 binary so no one should be stuck upgrading from 419.
