### ISSUE TITLE
[bug] S3 Connection Errors in Groups 

### ISSUE THREAD

**Issue by knoidy** [jalehman/port#227]
**Bug Description**
On Windows 11, trying to upload a file to Groups in Port produces error:
```
Cannot read properties of undefined (reading 'call')
Please check S3 settings.
```

**To Reproduce**
1. Go to Groups
2. In any chat, click on the paperclip icon after connection S3 bucket
3. Paperclip icon replaced by an exclamation point and the above message appears on rollover.

**Expected Behavior**
Image/file uploaded to chat.

**Environment:**
 - OS: Windows
 - Version: 11
 - Port Version: 1.9.1

**Additional context**
%Silo works correctly and the upload file function works on Chrome, only get this error when using Groups inside of Port

**Comment by arthyn** [comment]
Hey there I don't think this is a bug in port, there's an issue with the s3 uploads in groups. If you try hitting ctrl+R it'll likely fix it.

**Comment by knoidy** [comment]
works now!
